services:
  db:
    image: 'postgres:10-alpine'
    container_name: db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '5433:5432'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '8080:8080'
    env_file: .env